version: '3'
services:
backend:
build: ./backend
ports:
- "8080:8080"
environment:
SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/groupjagriapp
SPRING_DATASOURCE_USERNAME: yourUsername
SPRING_DATASOURCE_PASSWORD: yourPassword
frontend:
build: ./frontend
ports:
- "3000:3000"